test "replace expression":

	assert "hello this is a test" where "hello" is replaced with "goodbye" is "goodbye this is a test" with "replace"


	assert "hello this is a test" where "[el]" is regex replaced with "!" is "h!!!o this is a t!st" with "regex replace pattern 1"

	assert "hello this is a test" where "[el]" is replaced with "!" using regex is "h!!!o this is a t!st" with "regex replace pattern 2"


	set {_test::*} to "hello", "this", "is", "a", "test"

	assert {_test::*} where "hello", "tes" are replaced with "!" is ("!", "this", "is", "a", "!t") with "replace list"

	assert {_test::*} where "[el]" is regex replaced with "!" is "h!!!o", "this", "is", "a", "t!st" with "regex replace list"


	assert "aaaaAAAAbbbbBBBB" where "a" is replaced with "!" with case sensitivity is "!!!!AAAAbbbbBBBB" with "replace case sensitivity"